apps/contact/urls.py
from django.conf.urls.defaults import patterns, include, url
from contact.views import ContactView

urlpatterns = patterns('',
    url(r'^$', ContactView.as_view(), name='contact'),
)

apps/portfolio/urls.py
from django.conf.urls.defaults import patterns, url
from portfolio.views import JobDetailView, JobListView

urlpatterns = patterns('',
    url(r'^$', JobListView.as_view(), name='job_list'),
    url(r'^(?P<slug>[\w_-]+)/$', JobDetailView.as_view(), name='job_detail'),
)

urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url

from django.contrib import admin
import haystack

from core.feeds import DiarioRssEntriesFeed, DiarioRssEntriesByTagFeed

# Autodiscover admin and haystack
admin.autodiscover()
haystack.autodiscover()

# Connect signal to diario
from django.db.models import signals
from django.contrib.comments.moderation import CommentModerator, moderator
from diario.models import Entry
from core.signals import replace_slideshare_shortcode, EntryModerator

signals.pre_save.connect(replace_slideshare_shortcode, sender=Entry)
moderator.register(Entry, EntryModerator)

# URL settings
handler500 = 'klauslaube.views.server_error'

urlpatterns = patterns('',
    # Blog feeds
    url(r'^feed/$', DiarioRssEntriesFeed(), name='diario_feed'),
    url(r'^tag/(?P<tag_name>[^/]+)/feed/$', DiarioRssEntriesByTagFeed(),
        name='diario_tag_feed'),

    # Blog urls
    url(r'', include('diario.urls.entries')),
    url(r'^tag/', include('diario.urls.tagged')),
    url(r'^comentarios/', include('django.contrib.comments.urls')),

    url(r'^portfolio/', include('portfolio.urls', namespace='portfolio')),
    url(r'^contato/', include('contact.urls', namespace='contact')),

    # Search urls
    url(r'^busca/', include('haystack.urls')),

    # Admin urls
    url(r'^admin/media_manager/', include('media_manager.urls',
        namespace='media_manager')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

apps/links/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _, ugettext as __

from links import managers


class Category(models.Model):
    title = models.CharField(_(u'Título'), max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    is_active = models.BooleanField(_('Ativo'), default=True)

    objects = models.Manager()
    actives = managers.ActiveManager()

    class Meta:
        verbose_name = __('Categoria')
        verbose_name_plural = __('Categorias')
        ordering = ('title', )

    def __unicode__(self):
        return self.title


class Link(models.Model):
    category = models.ForeignKey(Category, verbose_name=_('Categoria'))
    title = models.CharField(_(u'Título'), max_length=100)
    description = models.TextField(_(u'Descrição'), blank=True, null=True)
    href = models.URLField(_(u'Endereço'), verify_exists=False)
    is_active = models.BooleanField(_('Ativo'), default=True)

    objects = models.Manager()
    actives = managers.LinkActiveManager()

    class Meta:
        verbose_name = __('Link')
        verbose_name_plural = __('Links')
        ordering = ('category__title', 'title', )

    def __unicode__(self):
        return self.title

templates/aside.html
{% load i18n diario_tagged links_extras %}

<section class="module">
    {% link_list "encontre-me-em" %}
</section>

<section class="module">
    {% link_list "blogroll" %}
</section>

{% tag_cloud_for_entries as entries_tags with steps=20 min_count=2 distribution=linear %}
{% if entries_tags %}
    <section class="module">
        <h3 class="title">{% trans "Tags" %}</h3>

        <div class="tagcloud">
        {% for tag in entries_tags %}
        <a href="{% url diario-tagged-entry-list tag=tag %}" title="{{ tag }}" class="tag-{{ tag.font_size }}">{{ tag }}</a>
        {% endfor %}
        </div>
    </section>
{% endif %}

templates/base.html
{% load i18n compress seohelper_extras %}<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="{{ LANGUAGE_CODE }}"> <!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    {% block meta %}{% seo_header request.path %}{% endblock %}
    <meta name="author" content="Klaus Laube <kplaube [at] gmail [dot] com>" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <link rel="canonical" href="{{ request.build_absolute_uri }}" />
    <link rel="shortcut icon" href="{{ STATIC_URL }}img/favicon.ico" />

    {% compress css %}
        {% block compressed_styles %}
            <link href="{{ STATIC_URL }}css/screen.css" media="screen, projection" rel="stylesheet" />
        {% endblock %}
        {% block styles %}
            <link href="{{ STATIC_URL }}css/print.css" media="print" rel="stylesheet" />
            <!--[if lt IE 8]>
                <link href="{{ STATIC_URL }}css/ie.css" media="screen, projection" rel="stylesheet" />
            <![endif]-->
        {% endblock %}
    {% endcompress %}

    {% block head_scripts %}
        <script src="{{ STATIC_URL }}js/libs/modernizr-2.0.6.min.js"></script>
    {% endblock %}

    {% block extras %}{% endblock %}
</head>
<body class="{% block body_class %}{% endblock %}">

<!-- root -->
<div id="root" class="container">
    <!-- header -->
    <header id="header" class="span-24 last">
        <!-- menu -->
        <nav id="menu">
            {% include "menu.html" with path=request.path %}
        </nav>
        <!-- end #menu -->

        <!-- logo -->
        <hgroup class="span-24 last">
            <h1 id="logo">
                <a href="{% url diario-entry-list %}" title="{% trans "Página inicial" %}">Klaus <span>Laube</span></a>
            </h1>
            <h2 class="hide">{% trans "Pythonista, Djangonauta e defensor dos padrões Web" %}</h2>
        </hgroup>
        <!-- end #logo -->

        <!-- quick-search -->
        {% include "quick_search.html" %}
        <!-- end #quick-search -->
    </header>
    <!-- end #header -->

    <!-- main -->
    <div id="main" class="span-24 last">
        {% block content_wrap %}
        <!-- content -->
        <div id="content" role="main" class="span-16 {% block content_class %}{% endblock %}">
            {% block content %}{% endblock %}
        </div>
        <!-- end #content -->
        {% endblock %}

        {% block aside_wrap %}
        <!-- aside -->
        <aside id="aside" class="span-7 last {% block aside_class %}{% endblock %}">
            {% block aside %}
                {% include "aside.html" %}
            {% endblock %}
        </aside>
        <!-- end #aside -->
        {% endblock %}
    </div>
    <!-- end #main -->
</div>
<!-- end #root -->

<!-- footer -->
<footer id="footer">
    <!-- container -->
    <div class="container">
        {% comment %}
        <nav class="col module">
            <h4 class="title">Consectetuer</h4>

            <ul>
                <li><a href="#">Aliquam libero</a></li>
                <li><a href="#">Aliquam libero</a></li>
                <li><a href="#">Aliquam libero</a></li>
                <li><a href="#">Aliquam libero</a></li>
                <li><a href="#">Aliquam libero</a></li>
                <li><a href="#">Aliquam libero</a></li>
            </ul>
        </nav>
        {% endcomment %}

        <div id="made-with">
            <p>{% blocktrans %}
                Funcionando com
                <a href="http://python.org/" title="Linguagem de programação Python">Python {{ PYTHON_VERSION }}</a> /
                <a href="http://www.djangoproject.com/" title="Framework Web para perfeccionistas com deadlines">Django {{ DJANGO_VERSION }}</a> /
                <a href="https://bitbucket.org/semente/django-diario/src" title="Engine de Blog para Django">django-diario {{ DIARIO_VERSION }}</a>.
                O código deste website é open source, e está disponível no 
                <a href="https://bitbucket.org/kplaube/klauslaube.com.br" title="Visite o repositório">Bitbucket</a>.
            {% endblocktrans %}</p>

            <p>{% blocktrans %}Estilos inspirados no <em>prepaid</em>, por
                <a href="http://www.freecsstemplates.org/" title="Free CSS Templates">CSS Templates</a>.
            {% endblocktrans %}</p>
        </div>

        <div id="copyright">{% blocktrans %}
            <p>O conteúdo deste blog está sob a licença 
                <a href="http://creativecommons.org/licenses/by/3.0/deed.pt_BR"
                title="Leia mais sobre a licença de uso do conteúdo deste blog">Creative 
                Commons Atribuição 3.0</a>.</p>
            <p>Compartilhe, modifique, usufrua. Mas
            mencione o autor.</p>
        {% endblocktrans %}</div>
    </div>
    <!-- end .container -->
</footer>
<!-- end #footer -->

<!-- scripts -->
{% block jquery_scripts %}
<script src="http://ajax.googleapis.com/ajax/libs/dojo/1.7.1/dojo/dojo.js"></script>
<script>window.dojo || document.write('<script src="{{ STATIC_URL }}js/libs/dojo-1.7.1.min.js"><\/script>')</script>
{% endblock %}

{% compress js %}
    {% block compressed_scripts %}
    <script defer src="{{ STATIC_URL }}js/script.js"></script>
    {% endblock %}

    {% block scripts %}{% endblock %}
{% endcompress %}

{% block google_analytics_scripts %}
<script>
    var _gaq=[['_setAccount','{{ GOOGLE_ANALYTICS_KEY }}'],['_trackPageview'],['_trackPageLoadTime']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
</script>
{% endblock %}

{% block crossbrowser_scripts %}
<!--[if lt IE 7 ]>
    <script defer src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
    <script defer>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
<![endif]-->
{% endblock %}

<!-- end scripts -->
</body>
</html>

templates/menu.html
{% load i18n core_extras %}

<ul>
    <li class="{% current path "^/((\d{4})/(\d{2})/(\d{2})/([-\w]+)/|tag/([-\w]+)/)?$" %}">
        <a href="{% url diario-entry-list %}" title="{% trans "Leia posts escritos por mim" %}">{% trans "Blog" %}</a>
    </li>
    <li class="{% current path "^/portfolio/" %}">
        <a href="{% url portfolio:job_list %}" title="{% trans "Confira os meus trabalhos" %}">{% trans "Portfolio" %}</a>
    </li>
    <li class="{% current path "^/sobre/$" %}">
        <a href="/sobre/" title="{% trans "Saiba mais sobre a minha pessoa" %}">{% trans "Sobre" %}</a>
    </li>
    <li class="{% current path "^/contato/$" %}">
    <a href="{% url contact:contact %}" title="{% trans "Fale comigo!" %}">{% trans "Contato" %}</a>
    </li>
</ul>

templates/messages.html
{% load i18n %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {{ message }}
        </li>
    {% endfor %}
</ul>
{% endif %}

templates/pagination.html
{% load i18n %}

{% if is_paginated %}
    <div class="pagination">
        {% if page_obj.has_previous %}
        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}{% if q %}&q={{ q }}{% endif %}"
                title="{% trans "Página anterior" %}">&lt; {% trans "Anterior" %}</a>
        {% endif %}

        {% for i in paginator.page_range %}
            <a href="{{ request.path }}?page={{ i }}{% if q %}&q={{ q }}{% endif %}"
                title="{% blocktrans %}Ir para a página {{ i }}{% endblocktrans %}"
                {% if page_obj.number == i %}class="current"{% endif %}>{{ i }}</a>
        {% endfor %}

        {% if page_obj.has_next %}
            <a href="{{ request.path }}?page={{ page_obj.next_page_number }}{% if q %}&q={{ q }}{% endif %}"
                title="{% trans "Próxima página" %}">{% trans "Próxima" %} &gt;</a>
        {% endif %}
    </div>
{% endif %}

templates/quick_search.html
{% load i18n %}

<form id="quick-search" action="/busca/" method="get">
    <p>
        <input type="search" id="q_id" name="q" placeholder="{% trans "informe a palavra-chave..." %}"
            {% if form.q.value %}value="{{ form.q.value }}"{% endif %}>
        <button type="submit">{% trans "Buscar" %}</button>
    </p>
</form>