apps/contact/urls.py
from django.conf.urls.defaults import patterns, include, url
from contact.views import ContactView

urlpatterns = patterns('',
    url(r'^$', ContactView.as_view(), name='contact'),
)

apps/portfolio/urls.py
from django.conf.urls.defaults import patterns, url
from portfolio.views import JobDetailView, JobListView

urlpatterns = patterns('',
    url(r'^$', JobListView.as_view(), name='job_list'),
    url(r'^(?P<slug>[\w_-]+)/$', JobDetailView.as_view(), name='job_detail'),
)

urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url

from django.contrib import admin
import haystack

from core.feeds import DiarioRssEntriesFeed, DiarioRssEntriesByTagFeed

# Autodiscover admin and haystack
admin.autodiscover()
haystack.autodiscover()

# Connect signal to diario
from django.db.models import signals
from django.contrib.comments.moderation import CommentModerator, moderator
from diario.models import Entry
from core.signals import replace_slideshare_shortcode, EntryModerator

signals.pre_save.connect(replace_slideshare_shortcode, sender=Entry)
moderator.register(Entry, EntryModerator)

# URL settings
handler500 = 'klauslaube.views.server_error'

urlpatterns = patterns('',
    # Blog feeds
    url(r'^feed/$', DiarioRssEntriesFeed(), name='diario_feed'),
    url(r'^tag/(?P<tag_name>[^/]+)/feed/$', DiarioRssEntriesByTagFeed(),
        name='diario_tag_feed'),

    # Blog urls
    url(r'', include('diario.urls.entries')),
    url(r'^tag/', include('diario.urls.tagged')),
    url(r'^comentarios/', include('django.contrib.comments.urls')),

    url(r'^portfolio/', include('portfolio.urls', namespace='portfolio')),
    url(r'^contato/', include('contact.urls', namespace='contact')),

    # Search urls
    url(r'^busca/', include('haystack.urls')),

    # Admin urls
    url(r'^admin/media_manager/', include('media_manager.urls',
        namespace='media_manager')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

apps/seohelper/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _

ROBOT_TAGS = (
    ('index,follow', 'Index, Follow'),
    ('noindex,follow', 'No index, Follow'),
    ('index,nofollow', 'Index, No follow'),
    ('noindex,nofollow', 'No index, No follow'),
)


class ObjectMeta(object):
    default_robot_tag = ROBOT_TAGS[3][0]

    def __init__(self, object_detail):
        if type(object_detail) == dict:
            get_value = self._get_value_from_dict
        else:
            get_value = self._get_value_from_object

        self.title = get_value(object_detail, 'title')
        self.description = get_value(object_detail, 'description')
        self.keywords = get_value(object_detail, 'keywords')
        self.robot_tags = get_value(object_detail, 'robot_tags',
            self.default_robot_tag)

    def _get_value_from_object(self, object_, index, default_value=None):
        return getattr(object_, index, default_value)

    def _get_value_from_dict(self, dict_, index, default_value=None):
        return dict_.get(index, default_value)


class Document(models.Model):
    url = models.CharField(_(u'URL'), max_length=255)
    title = models.CharField(_(u'Título'), max_length=140)
    description = models.TextField(_(u'Descrição'), blank=True, null=True)
    keywords = models.CharField(
        _(u'Palavras-chave'),
        max_length=255,
        blank=True,
        null=True,
    )
    robot_tags = models.CharField(
        _(u'Robots'),
        max_length=20,
        choices=ROBOT_TAGS,
        default=ROBOT_TAGS[0][0],
    )

    class Meta:
        verbose_name = _('Documento')
        verbose_name_plural = _('Documentos')
        ordering = ('url', )

    def __unicode__(self):
        return self.title

apps/contact/forms.py
# -*- coding: utf-8 -*-

from django.core import mail
from django import forms
from django.template.loader import render_to_string
from django.utils.translation import ugettext_lazy as _

from contact import settings


class ContactForm(forms.Form):
    name = forms.CharField(label=_('Nome'), max_length=100)
    email = forms.EmailField(label=_('E-mail'))
    subject = forms.CharField(label=_('Assunto'), max_length=255)
    message = forms.CharField(
        label=_('Mensagem'),
        widget=forms.Textarea(),
    )

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)

        # Settings HTML5 attributes to fields
        self.fields['name'].widget.attrs.update({
            'autofocus': 'true',
            'placeholder': _('Seu nome...'),
        })
        self.fields['email'].widget.input_type = 'email'
        self.fields['email'].widget.attrs.update({
            'placeholder': _('seu-email@provedor.com.br'),
        })
        self.fields['subject'].widget.attrs.update({
            'placeholder': _(u'O título do seu e-mail'),
        })
        self.fields['message'].widget.attrs.update({
            'placeholder': _('Sua mensagem...'),
        })

        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'required': 'true',
            })

    def send(self, to_email=settings.SITE_EMAIL):
        message = render_to_string('contact/contact_email.html',
            self.cleaned_data)

        return mail.send_mail(
            self.cleaned_data['subject'],
            self.cleaned_data['message'],
            self.cleaned_data['email'],
            [to_email, ],
            fail_silently=True,
        )

templates/comments/base.html
{% extends "base.html" %}
{% load i18n seohelper_extras %}

{% block meta %}{% seo_custom_header "Comentários" %}{% endblock %}

{% block content_class %}posts{% endblock %}

templates/comments/form.html
{% load comments i18n %}

<form id="comment-form" action="{% comment_form_target %}" method="post">
    {% csrf_token %}

    <div class="hidden">
        {% if next %}<input type="hidden" name="next" value="{{ next }}" />{% endif %}

        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
    </div>

    {% with field=form.name %}
        <p>
            {{ field.label_tag }}

            <input type="text" id="id_name" name="name" maxlength="50"
                {% if field.value %}value="{{ field.value }}"{% endif %}
                placeholder="{% trans "Seu nome ou apelido" %}" required>

            {% if field.help_text %}
                <small class="help-text">{{ field.help_text }}</small>
            {% endif %}

            {{ field.errors }}
        </p>
    {% endwith %}

    {% with field=form.email %}
        <p>
            {{ field.label_tag }}

            <input type="email" id="id_email" name="email"
                {% if field.value %}value="{{ field.value }}"{% endif %}
                placeholder="{% trans "seu-email@provedor.com.br" %}" required>

            {% if field.help_text %}
                <small class="help-text">{{ field.help_text }}</small>
            {% endif %}

            {{ field.errors }}
        </p>
    {% endwith %}

    {% with field=form.url %}
        <p>
            {{ field.label_tag }}

            <input type="url" id="id_url" name="url"
                {% if field.value %}value="{{ field.value }}"{% endif %}
                placeholder="{% trans "http://seu-website.com.br" %}">

            {% if field.help_text %}
                <small class="help-text">{{ field.help_text }}</small>
            {% endif %}

            {{ field.errors }}
        </p>
    {% endwith %}

    {% with field=form.comment %}
        <p>
            {{ field.label_tag }}

            <textarea id="id_comment" name="comment" rows="10" cols="40"
                required placeholder="{% trans "Seu comentário..." %}">{% if field.value %}{{ field.value }}{% endif %}</textarea>

            {% if field.help_text %}
                <small class="help-text">{{ field.help_text }}</small>
            {% endif %}

            {{ field.errors }}
        </p>
    {% endwith %}

    {% with field=form.honeypot %}
        <p>
            {{ field.label_tag }}

            {{ field }}

            {% if field.help_text %}
                <small class="help-text">{{ field.help_text }}</small>
            {% endif %}

            {{ field.errors }}
        </p>
    {% endwith %}

    <p>
        <input type="submit" name="submit" value="{% trans "Enviar" %}" class="button">
    </p>
</form>

templates/comments/list.html
{% for comment in comment_list %}
    <article class="comment">
        <header>
            <h4 class="comment-title">
                {% if comment.user_url %}
                <a href="{{ comment.user_url }}" rel="nofollow">{{ comment.user_name }}</a>:
                {% else %}
                    {{ comment.user_name }}:
                {% endif %}
            </h4>

            <time pubdate datetime="{{ comment.submit_date|date:"Y-m-d H:i:s" }}">
                {{ comment.submit_date|date:"l, d \d\e F \d\e Y. H:i" }}
            </time>
        </header>

        <div>{{ comment.comment|linebreaks }}</div>

    </article>
{% endfor %}

templates/comments/preview.html
{% extends "comments/base.html" %}
{% load i18n seohelper_extras %}

{% block meta %}{% seo_custom_header "Envio de comentários" %}{% endblock %}

{% block content %}
    <h2 class="title">{% trans "Envio de comentários" %}</h2>

    {% if form.errors %}
        <p>{% trans "Por favor, verifique se o formulário abaixo está com os campos obrigatórios preenchidos"  %}.</p>
    {% endif %}

    {% include "comments/form.html" %}
{% endblock %}